#!/bin/bash
# A simple script to select containers and images with fzf for bulk operations

# Test if fzf and docker are in PATH
if ! which docker fzf > /dev/null 2>&1
then
  echo "error: fzf is not installed"
  exit 1
fi

FZF='fzf --reverse'
FZFM='fzf --reverse -m'

case $1 in
stop)
  # Select and stop containers by their ID
  docker ps | tail -n +2 | $FZFM | awk '{print $1}' | xargs -r docker ${@:1}
  ;;
start)
  # Select and start containers by their ID
  docker ps -a | tail -n +2 | $FZFM | awk '{print $1}' | xargs -r docker ${@:1}
  ;;
inspect)
  # Select and inspect container by its ID
  ID=$(docker ps -a | tail -n +2 | $FZF | awk '{print $1}')
  [ -n "$ID" ] && docker ${@:1} $ID 2>&1 | less
  ;;
rm)
  # Select and remove containers by their ID
  docker ps -a | tail -n +2 | $FZFM | awk '{print $1}' | xargs -r docker ${@:1}
  ;;
rmi)
  # Select and remove images by their ID
  docker images | tail -n +2 | $FZFM | awk '{print $3}' | xargs -r docker ${@:1}
  ;;
rmt)
  # Select and remove images by their tags
  docker images | tail -n +2 | $FZFM | awk '{print $1 ":" $2}' | xargs -r docker rmi ${@:2}
  ;;
volume)
  case $2 in
  rm)
    # Select and remove volumes by their ID
    docker volume ls | tail -n +2 | $FZFM | awk '{print $2}' | xargs -r docker ${@:1}
    ;;
  inspect)
    # Select and inspect volume by its ID
    ID=$(docker volume ls | tail -n +2 | $FZF | awk '{print $2}')
    [ -n "$ID" ] && docker ${@:1} $ID 2>&1 | less
    ;;
  *)
    echo "error: unsupported command '$@'"
    exit 1
    ;;
  esac
  ;;
network)
  case $2 in
  rm)
    # Select and remove networks by their ID
    docker network ls | tail -n +2 | $FZFM | awk '{print $1}' | xargs -r docker ${@:1}
    ;;
  inspect)
    # Select and inspect network by its ID
    ID=$(docker network ls | tail -n +2 | $FZF | awk '{print $1}')
    [ -n "$ID" ] && docker ${@:1} $ID 2>&1 | less
    ;;
  *)
    echo "error: unsupported command '$@'"
    exit 1
    ;;
  esac
  ;;
*)
  echo "error: unsupported command '$@'"
  exit 1
  ;;
esac
